name = "mec-class"
compatibility_date = "2025-08-04"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "mec-class-db"
database_id = "5a0aab92-e536-4eb1-94cf-3c8da28a970e"

[vars]
ADMIN = "teacher123"
