name = "mec-class"
compatibility_date = "2025-08-04"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "mec-class-db"
database_id = "REPLACE_WITH_YOUR_D1_ID"

[vars]
ADMIN = "teacher123"
